number-depth: 2
project:
  type: book
book:
  title: ""
  author: ""
  favicon: ICArEHB_V_Color.png
  sidebar: 
    logo: images/cover3.png
    search: true
    
  reader-mode: false
  
  chapters:
    - index.qmd
    - policy.qmd
    - publishing.qmd
    - data.qmd
    - preregistration.qmd
    - methods.qmd
    - peerreview.qmd
    - tools.qmd
    - improvements.qmd
  appendices:
    - glossary.qmd

format:
  html:
    theme: [cosmo, custom.scss]
    code-link: true
  asciidoc: default
  pdf:
    documentclass: scrreprt

editor: visual

